arm:
  type: ur10
  initial_joint_states:
    linear_arm_actuator_joint: 0

sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0, 0.5, 5]
      rpy: [0, 'pi/2', 0]
  laser_profiler:
    type: laser_profiler
    pose:
      xyz: [1.21816, 4, 1.61]
      rpy: ['-pi', 'pi/2', 'pi/2']

# plz run the below to test or substitute the yaml file every time launching gazebo
# rosrun osrf_gear gear.py -f `catkin_find --share osrf_gear`/config/qual1a.yaml `rospack find cwru_ariac`/config/vision.yaml
